server:
  port: 5002
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.12/spring_cloud_example_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: spring_cloud_example
    password: 123456
    initial-size: 5
    min-idle: 5
    max-idle: 10
    max-wait: 2000
  jpa:
    open-in-view: false
  redis:
    database: 0
    host: 192.168.3.12
    port: 6379
  data:
    redis:
      repositories:
        enabled: false

jwt:
  config:
    generateKey: guoguo
    duration: 1234567890
    parseKeys: guoguo