server:
  port: 5002

spring:
  datasource:
    url: jdbc:mysql://192.168.3.12/spring_cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: spring_cloud_demo
    password: 123456

jwt:
  config:
    generateKey: guoguo
    duration: 1234567890
    parseKeys: guoguo