server:
  port: 5007

spring:
  datasource:
    url: jdbc:mysql://192.168.3.2:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: test
    password: 123456

test:
  name: guoguoguo