server:
  port: 5007

spring:
  datasource:
    url: jdbc:mysql://192.168.3.2:3307/spring_cloud_example?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: spring_cloud_example
    password: 123456

schedule:
  test-task:
    cron: "0/30 * * * * ?"

test:
  name: guoguoguo