server:
  port: 5007

spring:
  datasource:
    url: jdbc:mysql://192.168.3.12/spring_cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: spring_cloud_demo
    password: 123456

test:
  name: guoguoguo