spring:
  cloud:
    gateway:
      default-filters:
        - name: TimeLog
          args:
            threshold: 3000
      routes:
        - id: ACCOUNT
          uri: lb://ACCOUNT
          predicates:
            - Path=/api/account/**
        - id: PRODUCER
          uri: lb://PRODUCER
          predicates:
            - Path=/api/producer/**
        - id: CONSUMER
          uri: lb://CONSUMER
          predicates:
            - Path=/api/consumer/**
